
(function(){
  'use strict';
  const P=state.premium=state.premium||{humanize:0,velocity:100,probability:100,density:60,bass:{steps:Array(16).fill(0),root:'C',oct:2,vol:.7,glide:.2},fx:{drive:0,air:50,glue:40}};
  P.bass=P.bass||{steps:Array(16).fill(0),root:'C',oct:2,vol:.7,glide:.2}; P.bass.steps=Array.isArray(P.bass.steps)?P.bass.steps:Array(16).fill(0); while(P.bass.steps.length<16)P.bass.steps.push(0); P.bass.steps=P.bass.steps.slice(0,16);
  function q(id){return document.getElementById(id)} function pct(id,v){const e=q(id);if(e)e.textContent=Math.round(v)+'%'}
  function save(){try{saveCurrentSong()}catch(e){try{scheduleSave()}catch(_){} }}
  function renderBass(){const h=q('bassSteps');if(!h)return;h.innerHTML='';P.bass.steps.forEach((v,i)=>{const b=document.createElement('button');b.type='button';b.className='bass-step'+(v?' on':'');b.dataset.step=i+1;b.title='808 step '+(i+1);b.addEventListener('click',()=>{P.bass.steps[i]=P.bass.steps[i]?0:1;b.classList.toggle('on',!!P.bass.steps[i]);save();});h.appendChild(b)});}
  window.playPremiumBass=function(t,step){try{const c=ensureAudio(), root=q('bassRoot')?.value||P.bass.root||'C', oct=Number(q('bassOct')?.value||P.bass.oct||2), vol=Number(q('bassVol')?.value||70)/100;P.bass.root=root;P.bass.oct=oct;P.bass.vol=vol;const f=(NOTE_FREQ[root]||261.63)*Math.pow(2,oct-4),o=c.createOscillator(),g=c.createGain(),filt=c.createBiquadFilter();o.type='sine';o.frequency.setValueAtTime(f,t);const gl=Number(q('bassGlide')?.value||20)/100;if(gl>.01)o.frequency.exponentialRampToValueAtTime(f*(step%4===3?1.5:1),t+.06+gl*.12);filt.type='lowpass';filt.frequency.value=420;filt.Q.value=1.1;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(Math.max(.02,vol*.55),t+.008);g.gain.exponentialRampToValueAtTime(.001,t+.22+gl*.15);o.connect(filt);filt.connect(g);g.connect(liveDest('bass'));o.start(t);o.stop(t+.45)}catch(e){}}
  function setSlider(id,key,unit){const el=q(id);if(!el)return;const apply=()=>{P[key]=Number(el.value);const out=q(id+'Val');if(out)out.textContent=Math.round(Number(el.value))+(unit||'%');if(key==='humanize'||key==='velocity'||key==='probability'){try{buildTracks();updateDNA()}catch(e){}}try{save()}catch(e){}};el.value=P[key];el.addEventListener('input',apply);apply()}
  // Premium swing mirrors the main swing control; do not bind a phantom _swing state.
  // premium swing mirrors the existing swing control
  const ps=q('proSwing'); if(ps){ps.value=state.swing||0; ps.addEventListener('input',()=>{state.swing=Number(ps.value);const base=q('swingSlider');if(base)base.value=ps.value;const v=q('swingVal');if(v)v.textContent=ps.value+'%';pct('proSwingVal',ps.value);save();});pct('proSwingVal',state.swing||0)}
  setSlider('proHuman','humanize');setSlider('proVel','velocity');setSlider('proProb','probability');
  const den=q('aiDensity');if(den){den.value=P.density||60;den.addEventListener('input',()=>{P.density=Number(den.value);pct('aiDensityVal',P.density);try{save()}catch(e){}});pct('aiDensityVal',P.density)}
  const bv=q('bassVol');if(bv){bv.value=Math.round(P.bass.vol*100);bv.addEventListener('input',()=>{P.bass.vol=Number(bv.value)/100;pct('bassVolVal',bv.value);try{save()}catch(e){}})}pct('bassVolVal',P.bass.vol*100);
  const bg=q('bassGlide');if(bg){bg.value=Math.round(P.bass.glide*100);bg.addEventListener('input',()=>{P.bass.glide=Number(bg.value)/100;pct('bassGlideVal',bg.value);try{save()}catch(e){}})}pct('bassGlideVal',P.bass.glide*100);
  q('bassRoot')?.addEventListener('change',e=>{P.bass.root=e.target.value;save()}); q('bassOct')?.addEventListener('change',e=>{P.bass.oct=Number(e.target.value);save()});
  function syncPremiumUI(){
    const vals={proHuman:P.humanize,proVel:P.velocity,proProb:P.probability,aiDensity:P.density,bassVol:P.bass.vol*100,bassGlide:P.bass.glide*100,proSwing:state.swing||0};
    Object.keys(vals).forEach(id=>{const e=q(id);if(e)e.value=vals[id]});
    pct('proHumanVal',P.humanize);pct('proVelVal',P.velocity);pct('proProbVal',P.probability);pct('aiDensityVal',P.density);pct('bassVolVal',P.bass.vol*100);pct('bassGlideVal',P.bass.glide*100);pct('proSwingVal',state.swing||0);
    ['drive','air','glue'].forEach(k=>{const e=q('fx'+k.charAt(0).toUpperCase()+k.slice(1)); if(e)e.value=P.fx?.[k]??(k==='air'?50:k==='glue'?40:0); const o=q('fx'+k.charAt(0).toUpperCase()+k.slice(1)+'Val'); if(o)o.textContent=(e?e.value:0)+'%';});
    if(q('bassRoot'))q('bassRoot').value=P.bass.root||'C'; if(q('bassOct'))q('bassOct').value=String(P.bass.oct||2);
  }
  syncPremiumUI();
  window.syncPremiumUI=syncPremiumUI;
  function randomPattern(density,hard){const n=state.stepCount||16, p=state.pattern;['kick','snare','hat','clap'].forEach(k=>p[k]=Array.from({length:n},(_,i)=>{if(k==='kick'&&i%4===0)return 1;if(k==='snare'&&i%8===4)return 1;if(k==='hat'&&i%2===0&&density>.35)return 1;let d=density*(k==='hat'?1.35:k==='clap'?.45:1);if(hard)d*=1.25;return Math.random()<Math.min(.95,d)?1:0;}));buildTracks();updateDNA();save()}
  function generate(){const g=(q('aiGenre')?.value||'Afrobeat').toLowerCase();const map={afrobeat:'afro',amapiano:'amapiano',trap:'trap',drill:'drill','hip-hop':'hiphop','lo-fi':'lofi',house:'house',dancehall:'dancehall','r&b':'rnb',gospel:'gospel',techno:'techno'};const kit=map[g]||'afro';const base=KITS[kit]||KITS.afro;state.kit=kit;const n=state.stepCount||16,d=(P.density||60)/100,e=q('aiEnergy')?.value||'mid',mult={low:.7,mid:1,high:1.2,max:1.4}[e]||1;['kick','snare','hat','clap'].forEach(k=>{const a=[];for(let i=0;i<n;i++){const src=base[k][i%base[k].length];let hit=src?1:((Math.random()<d*.22*mult)?1:0);if(k==='kick'&&i%4===0)hit=1;if(k==='snare'&&i%8===4)hit=1;a.push(hit)}p=0;state.pattern[k]=a});buildTracks();updateDNA();save();toast('AI beat generated')}
  function mutate(amount){const n=state.stepCount||16;['kick','snare','hat','clap'].forEach(k=>{state.pattern[k]=state.pattern[k].map((v,i)=>{if(k==='kick'&&i%4===0)return 1;if(k==='snare'&&i%8===4)return 1;return Math.random()<amount?(v?0:1):v})});buildTracks();updateDNA();save()}
  function simplify(){const n=state.stepCount||16;['kick','snare','hat','clap'].forEach(k=>{state.pattern[k]=state.pattern[k].map((v,i)=>{if(k==='kick'&&i%4===0)return 1;if(k==='snare'&&i%8===4)return 1;if(!v)return 0;return Math.random()<0.28?0:1})});buildTracks();updateDNA();save();toast('Pattern simplified')}
  function fill(kind){const n=state.stepCount||16;const a=state.pattern.snare;const start=Math.max(0,n-4), mult={subtle:1,medium:1.5,crazy:2.2}[kind]||1;a[n-1]=1;if(kind!=='subtle')a[n-2]=1;state.pattern.hat[n-1]=1;if(kind!=='subtle')state.pattern.hat[n-2]=1;if(kind==='crazy'){for(let i=start;i<n;i++)a[i]=i%2?1:0;state.pattern.clap[n-2]=1}buildTracks();updateDNA();save();toast(kind+' fill added')}
  function template(name){const n=state.stepCount||16;const src=JSON.parse(JSON.stringify(state.pattern));if(name==='intro'){['kick','snare','hat','clap'].forEach(k=>src[k]=src[k].map((v,i)=>i<4?0:v));}if(name==='verse'){src.hat=src.hat.map((v,i)=>i%2?0:v)}if(name==='chorus'){src.hat=src.hat.map(()=>1);src.clap=src.clap.map((v,i)=>v||i%8===6?1:0)}if(name==='outro'){['kick','snare','hat','clap'].forEach(k=>src[k]=src[k].map((v,i)=>i>=n-4?0:v));}state.pattern=src;buildTracks();updateDNA();save();toast(name+' pattern applied')}
  function updateDNA(){const n=state.stepCount||16,total=['kick','snare','hat','clap'].reduce((a,k)=>a+(state.pattern[k]||[]).filter(Boolean).length,0),density=Math.min(100,total/(n*4)*100);const transitions=['kick','snare','hat','clap'].reduce((a,k)=>a+(state.pattern[k]||[]).reduce((x,v,i)=>x+(i&&v!==state.pattern[k][i-1]?1:0),0),0);const energy=Math.min(100,Math.round(density*.75+(P.velocity||100)*.18));const groove=Math.round((state.swing||0)*.7+(P.humanize||0)*.3);const variation=Math.min(100,Math.round(transitions/(n*4)*100));[['dnaEnergy',energy],['dnaGroove',groove],['dnaDensity',Math.round(density)],['dnaVariation',variation]].forEach(([id,v])=>{const e=q(id);if(e)e.textContent=v+'%'});}
  q('generateBeatBtn')?.addEventListener('click',generate);q('variationBtn')?.addEventListener('click',()=>mutate(.14));q('simplifyBtn')?.addEventListener('click',simplify);q('harderBtn')?.addEventListener('click',()=>{P.density=Math.min(90,(P.density||60)+12);if(q('aiDensity'))q('aiDensity').value=P.density;generate()});q('humanizeBtn')?.addEventListener('click',()=>{P.humanize=Math.max(25,P.humanize||0);if(q('proHuman'))q('proHuman').value=P.humanize;pct('proHumanVal',P.humanize);toast('Human feel applied')});q('tightenBtn')?.addEventListener('click',()=>{P.humanize=0;if(q('proHuman'))q('proHuman').value=0;pct('proHumanVal',0);state.swing=Math.min(10,state.swing||0);if(q('proSwing'))q('proSwing').value=state.swing;toast('Pattern tightened')});document.querySelectorAll('[data-fill]').forEach(b=>b.addEventListener('click',()=>fill(b.dataset.fill)));q('dropBtn')?.addEventListener('click',()=>{const n=state.stepCount||16;['kick','snare','hat','clap'].forEach(k=>state.pattern[k]=state.pattern[k].map((v,i)=>i<n/2?0:v));buildTracks();updateDNA();save();toast('Drop created')});['intro','verse','chorus','outro'].forEach(n=>q(n+'Btn')?.addEventListener('click',()=>template(n)));q('remixDnaBtn')?.addEventListener('click',()=>{mutate(.2);state.swing=Math.min(60,Math.max(10,(state.swing||0)+Math.floor(Math.random()*20)));if(q('proSwing'))q('proSwing').value=state.swing;pct('proSwingVal',state.swing);toast('DNA remixed')});
  document.querySelectorAll('[data-fx]').forEach(el=>el.addEventListener('input',()=>{P.fx=P.fx||{};P.fx[el.dataset.fx]=Number(el.value);const o=q('fx'+el.dataset.fx.charAt(0).toUpperCase()+el.dataset.fx.slice(1)+'Val');if(o)o.textContent=el.value+'%';if(el.dataset.fx==='glue')state.glue=Number(el.value);try{syncLiveGraphLevels()}catch(e){};save()}));
  // Keep DNA and premium controls in sync whenever the existing mixer rebuilds.
  const oldBuild=window.buildTracks;if(oldBuild&&!oldBuild.__premium){window.buildTracks=function(){const r=oldBuild.apply(this,arguments);renderBass();updateDNA();return r};window.buildTracks.__premium=true}
  renderBass();updateDNA();
})();

(function(){
  const status=document.getElementById('beatLabStatus');
  const setStatus=(msg)=>{if(status){status.textContent=msg;clearTimeout(setStatus._t);setStatus._t=setTimeout(()=>status.textContent='Ready',1800)}};
  ['generateBeatBtn','variationBtn','simplifyBtn','harderBtn','humanizeBtn','tightenBtn','remixDnaBtn','dropBtn','introBtn','verseBtn','chorusBtn','outroBtn'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener('click',()=>setStatus('Applied'));});
  document.querySelectorAll('[data-fill]').forEach(el=>el.addEventListener('click',()=>setStatus(el.textContent.replace(' Fill',''))));
  document.querySelectorAll('[data-beat-preset]').forEach(btn=>btn.addEventListener('click',()=>{
    const key=btn.dataset.beatPreset;
    const genre=document.getElementById('genreSelect'); if(genre){const map={afro:'afro',trap:'trap',amapiano:'amapiano',lofi:'lofi'};genre.value=map[key]||key;genre.dispatchEvent(new Event('change',{bubbles:true}));}
    const ai=document.getElementById('aiGenre'); if(ai){const map={afro:'Afrobeat',trap:'Trap',amapiano:'Amapiano',lofi:'Lo-Fi'};ai.value=map[key]||ai.value;}
    setStatus(btn.textContent+' loaded');
  }));
})();
