-- Tapehead Pro production security hardening.
-- Run after supabase-schema.sql and supabase-air.sql.

-- 1) Public artist profiles must not expose email/contact or billing state.
drop policy if exists "profiles read" on public.profiles;
drop policy if exists "profiles upsert own" on public.profiles;
create policy "profiles read own" on public.profiles for select using (auth.uid() = id);
create policy "profiles insert own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles update own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "profiles delete own" on public.profiles for delete using (auth.uid() = id);

-- Safe public projection used by artist profiles. It intentionally excludes contact,
-- is_pro and pro_until. The underlying table remains protected by RLS.
create or replace view public.public_profiles as
select id, username, avatar_url, bio, location, genres, links, open_to_collab
from public.profiles;
grant select on public.public_profiles to anon, authenticated;

-- 2) Collaboration rooms: anyone can look up a room by its code to join,
-- but only the host can modify/delete the room.
drop policy if exists "rooms write auth" on public.rooms;
drop policy if exists "rooms insert own" on public.rooms;
drop policy if exists "rooms update host" on public.rooms;
drop policy if exists "rooms delete host" on public.rooms;
create policy "rooms insert own" on public.rooms for insert with check (auth.uid() = host_id);
create policy "rooms update host" on public.rooms for update using (auth.uid() = host_id) with check (auth.uid() = host_id);
create policy "rooms delete host" on public.rooms for delete using (auth.uid() = host_id);

-- Members can only read a room after joining; use a SECURITY DEFINER helper
-- so the policy does not recursively query room_members under its own RLS policy.
create or replace function public.is_room_member(p_room_code text, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.room_members
    where room_code = p_room_code and user_id = p_user_id
  );
$$;
revoke all on function public.is_room_member(text, uuid) from public;
grant execute on function public.is_room_member(text, uuid) to anon, authenticated;

drop policy if exists "members read" on public.room_members;
drop policy if exists "members write" on public.room_members;
create policy "members read room members" on public.room_members for select using (
  auth.uid() = user_id or public.is_room_member(room_code, auth.uid())
);
create policy "members insert own" on public.room_members for insert with check (auth.uid() = user_id);
create policy "members delete own" on public.room_members for delete using (auth.uid() = user_id);

-- Vocal metadata and recordings are private to room members.
drop policy if exists "vocals read" on public.room_vocals;
drop policy if exists "vocals write" on public.room_vocals;
create policy "vocals read room members" on public.room_vocals for select using (
  exists (select 1 from public.room_members rm where rm.room_code = room_vocals.room_code and rm.user_id = auth.uid())
);
create policy "vocals insert room members" on public.room_vocals for insert with check (
  auth.uid() = user_id and exists (select 1 from public.room_members rm where rm.room_code = room_vocals.room_code and rm.user_id = auth.uid())
);
create policy "vocals delete own" on public.room_vocals for delete using (auth.uid() = user_id);

-- 3) Comments can be removed by their author.
drop policy if exists "comments delete own" on public.comments;
create policy "comments delete own" on public.comments for delete using (auth.uid() = user_id);

-- 4) AI usage ledger for server-side per-user rate limiting.
create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create index if not exists ai_usage_user_created_idx on public.ai_usage(user_id, created_at desc);
alter table public.ai_usage enable row level security;
revoke all on public.ai_usage from anon, authenticated;
-- The server uses the Supabase service role, which bypasses RLS.

-- 5) Make the vocal storage bucket private. Replace public URLs with signed URLs
-- in the application when this migration is enabled.
update storage.buckets set public = false where id = 'vocals';


-- 6) Private vocal storage policies. Object names are <user_id>/<room_code>_...
drop policy if exists "vocals public read" on storage.objects;
drop policy if exists "vocals authenticated upload" on storage.objects;
drop policy if exists "vocals own upload" on storage.objects;
drop policy if exists "vocals room read" on storage.objects;
drop policy if exists "vocals own delete" on storage.objects;
create policy "vocals room read" on storage.objects for select using (
  bucket_id = 'vocals'
  and exists (
    select 1 from public.room_members rm
    where rm.user_id = auth.uid()
      and rm.room_code = split_part(split_part(name, '/', 2), '_', 1)
  )
);
create policy "vocals own upload" on storage.objects for insert with check (
  bucket_id = 'vocals'
  and split_part(name, '/', 1) = auth.uid()::text
  and exists (
    select 1 from public.room_members rm
    where rm.user_id = auth.uid()
      and rm.room_code = split_part(split_part(name, '/', 2), '_', 1)
  )
);
create policy "vocals own delete" on storage.objects for delete using (
  bucket_id = 'vocals' and split_part(name, '/', 1) = auth.uid()::text
);

-- 7) Social safety: blocks and reports.
create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);
create index if not exists blocks_blocked_idx on public.blocks(blocked_id);
alter table public.blocks enable row level security;
drop policy if exists "blocks own" on public.blocks;
create policy "blocks own" on public.blocks for all using (auth.uid() = blocker_id) with check (auth.uid() = blocker_id);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_user_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (char_length(reason) between 1 and 80),
  created_at timestamptz not null default now()
);
create index if not exists reports_created_idx on public.reports(created_at desc);
alter table public.reports enable row level security;
drop policy if exists "reports create own" on public.reports;
create policy "reports create own" on public.reports for insert with check (auth.uid() = reporter_id);

-- Blocked users cannot receive new direct messages from the blocker relationship.
drop policy if exists "messages send" on public.messages;
create policy "messages send" on public.messages for insert with check (
  auth.uid() = sender_id
  and not exists (
    select 1 from public.blocks b
    where (b.blocker_id = auth.uid() and b.blocked_id = recipient_id)
       or (b.blocker_id = recipient_id and b.blocked_id = auth.uid())
  )
);
